version: "3"

services:

  server:
    image: mariapredescu/idpapp2_server:step2
    links:
      - database
    depends_on:
      - database
    ports: 
      - "5001:5000"
    networks:
      - frontend
      - backend
    restart: on-failure
    stdin_open: true
    tty: true

  client:
    image: mariapredescu/idpapp2_client:step2
    links:
      - server
    depends_on:
      - server
      - database
    ports:
      - "5002:5000"
    networks:
      - frontend
    stdin_open: true
    tty: true

  admin:
    build: ./admin
    links:
      - database
    depends_on:
      - database
    ports:
      - "5003:5000"
    networks:
      - backend
      - frontend
    restart: on-failure
    stdin_open: true
    tty: true

  database:
    image: mysql:5.7
    ports:
      - "32000:3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
networks:
  frontend:
  backend:
volumes:
  db_data: {}