 version: "2"

 services:

  server:
    build: ./listBooksApp
    links:
      - database
    ports: 
      - "5000:5000"

  database:
    image: mysql:5.7
    ports:
      - "32000:3306"
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234