version: "3"

services:

  server:
    image: mariapredescu/idpapp2_server:final
    links:
      - database
    depends_on:
      - database
    ports: 
      - "5001:5000"
    networks:
      - frontend
      - backend

  client:
    image: mariapredescu/idpapp2_client:step2
    links:
      - server
    depends_on:
      - server
      - database
    ports:
      - "5002:5000"
    networks:
      - frontend
    stdin_open: true
    tty: true

  admin:
    image: mariapredescu/idpapp2_admin:step3
    links:
      - database
    depends_on:
      - database
    ports:
      - "5003:5000"
    networks:
      - backend
      - frontend
    restart: on-failure
    stdin_open: true
    tty: true

  database:
    image: mysql:5.7
    ports:
      - "32000:3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  metrics:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_volume:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - backend
      - frontend

networks:
  frontend:
  backend:
volumes:
  db_data: {}
  prometheus_volume: {}